spring:
  datasource:
    url: jdbc:mysql://47.99.81.201:3306/db01
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.binbx.admin.*  #springbean监控
      filters: stat,wall,slf4j  #底层所有开启的功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:  #监控页配置
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter: #web监控
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: #对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true

        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false  #不允许删表


  jdbc:
    template:
      # 查询超时
      query-timeout: 3