#spring:
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
##    contentnegotiation:
##      favor-parameter: true
#  #  mvc:
#  #    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: [ classpath:/haha/]
#      #静态资源规则
#      add-mappings: true
#      #缓存时间
#      cache:
#        period: 11000
#server:
#  servlet:
#    context-path: /world

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true  # 开启页面表单的 Rest 风格功能
  #网络流量
  webflux:
    #静态路径模式
    static-path-pattern: /resources/**
  web:
    resources:
      static-locations: [classpath:/haha/]
      #静态资源规则
      add-mappings: true
      #缓存时间
      cache:
        period: 11000

server:
  servlet:
    context-path: /world